=== ctu-geoforall-lab-projects/bp-kratochvilova-2011/text/map_vystupy/psmap/krovak/metadata/non-iso/geodataCR.dtd
<!ELEMENT dataset   (mapset+)>
<!ELEMENT mapset    (rastr?, vektor?)>
<!ELEMENT rastr     (vrstva+)>
<!ELEMENT vektor    (vrstva+)>
<!ELEMENT vrstva    (nazev, popis, atributy, zdroj+, historie+)>
<!ELEMENT nazev     (#PCDATA)>
<!ELEMENT popis     (#PCDATA|mapa)*>
<!ELEMENT atributy  (atribut*)>
<!ELEMENT zdroj     (#PCDATA)>
<!ELEMENT historie  (#PCDATA)>
<!ELEMENT atribut   (#PCDATA)>
<!ELEMENT mapa      (#PCDATA)>

<!ATTLIST dataset
          popis     CDATA   #REQUIRED>
<!ATTLIST mapset
          id        ID      #REQUIRED
          verze     CDATA   #REQUIRED
          datum     CDATA   #REQUIRED>
<!ATTLIST vrstva
          id        ID      #REQUIRED
          stav      CDATA   #IMPLIED>
<!ATTLIST zmena
          pozn      CDATA   #IMPLIED
          title     CDATA   #IMPLIED>
<!ATTLIST atribut
          kod       CDATA   #IMPLIED>
<!ATTLIST zdroj
          title     CDATA   #IMPLIED
          pozn      CDATA   #IMPLIED>
<!ATTLIST historie
          text      CDATA   #REQUIRED>

<!ENTITY nbsp "&#160;">

=== ctu-geoforall-lab-projects/bp-kratochvilova-2011/text/map_vystupy/psmap/krovak/metadata/non-iso/popis_dat.xml
<?xml version="1.0" encoding="iso-8859-2"?>
<!DOCTYPE dataset SYSTEM "http://gama.fsv.cvut.cz/~landa/grasswikicz_data/geodata_cr/geodataCR.dtd">
<?xml-stylesheet href="geodataCR.xsl" type="text/xsl"?>

<dataset popis="Geografická data ÈR pro GRASS">
  <mapset id="PERMANENT" verze="0.3.0" datum="2005-03-21">
    <rastr>
      <vrstva id="dem_gtopo30">
	<nazev>digitální vý¹kový model (GTOPO30)</nazev>
	<popis>Jde o globální digitální vý¹kový model s prostorovým rozli¹ením
	30 úhlových vteøin (tj. pro území ÈR pøibli¾nì 900 x 600 m).
	Více informací naleznete na http://edcdaac.usgs.gov/gtopo30/README.asp.</popis>
	<atributy>
	  <atribut>vý¹ková data, rozsah: 123 - 1511 m</atribut>
	</atributy>
	<zdroj title="GTOPO30">http://lpdaac.usgs.gov/gtopo30/gtopo30.asp</zdroj>
	<historie text="pøidáno">0.2.0</historie>
      </vrstva>
      <vrstva id="dem_srtm">
	<nazev>digitální vý¹kový model (SRTM)</nazev>
	<popis>Prostorové rozli¹ení tìchto dat jsou 3 úhlové vteøiny,
	tj. pro území ÈR pøibli¾nì 90 x 60 m. Data byla poøízena pøi
	misi raketoplánu Endeavour - mohl tak vzniknout pomìrnì pøesný globální
	vý¹kový model (nasnímáno 80% povrchu sou¹e metodou radarové interferometrie).
	Maximální pøesnost tohoto modelu dosahuje 15 metrù v poloze a 12 metrù ve vý¹ce.</popis>
	<atributy>
	  <atribut>vý¹ková data, rozsah: 47 - 1594 m</atribut>
	</atributy>
	<zdroj title="SRTM">http://edcsgs9.cr.usgs.gov/pub/data/srtm/</zdroj>
	<historie text="pøidáno">0.2.0</historie>
      </vrstva>
    </rastr>
    <vektor>
      <vrstva id="casti_obce">
	<nazev>èásti obce</nazev>
	<popis>Vektorová mapa byla vygenerována na základì souøadnic ulo¾ených
	ve sloupcích "sxcob" a "sycob".</popis>
	<atributy>
	  <atribut kod="kn">kód kraje (pracovní)</atribut>
	  <atribut kod="knok">kód okresu (pracovní)</atribut>
	  <atribut kod="kodnuts">klasifikaèní jednotka NUTS</atribut>
	  <atribut kod="knuts">pracovní kódy okresù</atribut>
 	  <atribut kod="kodok">dosud platné kódy okresù</atribut>
	  <atribut kod="kodob">kód obce</atribut>
	  <atribut kod="ko">kontrolní znak</atribut>
	  <atribut kod="icob">identifikaèní èíslo obce</atribut>
	  <atribut kod="iczuj">identifikaèní èíslo základní územní jednotky</atribut>
	  <atribut kod="mo">mìstský obvod</atribut>
	  <atribut kod="mc">mìstská èást</atribut>
	  <atribut kod="kodcob">kód èásti obce</atribut>
	  <atribut kod="kc"></atribut>
	  <atribut kod="porcob">poøadí èásti obce v okrese</atribut>
	  <atribut kod="nazcob">název èásti obce</atribut>
	  <atribut kod="nazcob_a">název èásti obce (bez diakritiky)</atribut>
	  <atribut kod="nazcoba"></atribut>
	  <atribut kod="nazcoba_a"> (bez diakritiky)</atribut>
	  <atribut kod="kodcob_m">kód neèlenìné èásti obce podle MPSV</atribut>
	  <atribut kod="kcm">kontrolní znak neèlenìné èásti obce</atribut>
	  <atribut kod="nazdomcob"></atribut>
	  <atribut kod="nazdomcob_a"> (bez diakritiky)</atribut>
	  <atribut kod="psc">PSÈ</atribut>
	  <atribut kod="psc_2">druhé PSÈ v èásti obce</atribut>
	  <atribut kod="psc_3">tøetí PSÈ v èásti obce</atribut>
	  <atribut kod="psc_4">ètvrté PSÈ v èásti obce</atribut>
	  <atribut kod="psc_5">páté PSÈ v èásti obce</atribut>
	  <atribut kod="psc_6">¹esté PSÈ v èásti obce</atribut>
	  <atribut kod="psc_7">sedmé PSÈ v èásti obce</atribut>
	  <atribut kod="psc2">souhrná slo¾ka pro PSÈ</atribut>
	  <atribut kod="ob91">poèet obyvatel dle SLDB91</atribut>
	  <atribut kod="ob01">poèet obyvatel dle SLDB01</atribut>
	  <atribut kod="mapa">mapový list ZM10</atribut>
	  <atribut kod="sycob">souøadnice Y v S-JTSK</atribut>
	  <atribut kod="sxcob">souøadnice X v S-JTSK</atribut>
	  <atribut kod="porob">poøadí obce v okrese</atribut>
	  <atribut kod="pormc">poøadové èíslo mìstské èásti/mìstského obvodu</atribut>
	  <atribut kod="kodmc">kód mìstské èásti/mìstského obvodu</atribut>
	  <atribut kod="nazcs"></atribut>
	  <atribut kod="alkcob">alternativní (pùvodní) kód èásti obce</atribut>
	  <atribut kod="akc">alternativní (pùvodní) kontrolní znak èásti obce</atribut>
	  <atribut kod="zmenazaz">zmìna záznamu</atribut>
	  <atribut kod="zmenapol">zmìna polo¾ky</atribut>
	</atributy>
	<zdroj pozn="pouze atributy" title="Územnì identifikaèní registr">
	http://www0.mmr.cz/cgi-bin/sqw1250.cgi/uir/uir.sqw</zdroj>
	<historie text="pøidáno">0.2.1</historie>
      </vrstva>
      <vrstva id="cesty">
	<nazev>turistické trasy (okres ®ïár nad Sázavou)</nazev>
	<popis></popis>
	<atributy>
	  <atribut kod="rgntyp"></atribut>
	  <atribut kod="kod"></atribut>
	  <atribut kod="nazev">barva trasy</atribut>
	  <atribut kod="smer"></atribut>
	  <atribut kod="poityp"></atribut>
	  <atribut kod="kod_popis">popis</atribut>
	</atributy>
	<zdroj title="Free maps for Garmin Mapping GPS">http://gps-maps.info/cz</zdroj>
	<zdroj pozn="pouze atributy" title="TopoGuide CZ">
	http://home.tiscali.cz:8080/bytebox/topoguide</zdroj>
	<historie text="pøidáno">0.1.0</historie>
      </vrstva>
      <vrstva id="cfm">
	<nazev>rùzné, nezaøazeno</nazev>
	<popis></popis>
	<atributy>
	  <atribut kod="rgntyp"></atribut>
	  <atribut kod="kod"></atribut>
	  <atribut kod="nazev"></atribut>
	  <atribut kod="smer"></atribut>
	  <atribut kod="poityp"></atribut>
	  <atribut kod="kod_popis"></atribut>
	</atributy>
	<zdroj title="Free maps for Garmin Mapping GPS">http://gps-maps.info/cz/</zdroj>
	<zdroj pozn="pouze atributy" title="TopoGuide CZ">
	http://home.tiscali.cz:8080/bytebox/topoguide</zdroj> 
	<historie text="pøidáno">0.1.0</historie>
      </vrstva>
      <vrstva id="cr">
	<nazev>státní hranice ÈR</nazev>
	<popis>Ruènì upravená hranice ÈR z vrstvy hranice, pøevedená na plochu. Velmi pøibli¾ná!</popis>
	<atributy>
	  <atribut kod="nazev">oficiální název státu</atribut>
	  <atribut kod="nazev_a">oficiální název státu (bez diakritiky)</atribut>
	</atributy>
	<zdroj></zdroj>
	<historie text="pøidáno">0.1.0</historie>
      </vrstva>  
      <vrstva id="czfree_nodes"> 
	<nazev>uzly sítì CZFree</nazev> 
	<popis>CZFree.Net - projekt neziskové broadband telekomunikaèní sítì v Èeské Republice.</popis>
	<atributy></atributy>
	<zdroj title="CZFree">http://www.czfree.net</zdroj>
	<historie text="pøidáno">0.1.0</historie>
      </vrstva>
      <vrstva id="dsnimky"> 
	<nazev>náhledová mapa dru¾icových snímkù</nazev> 
	<popis>Mapa zobrazuje území pokrytá dru¾icovými daty, které jsou volnì dostupná
	na http://glcfapp.umiacs.umd.edu.</popis>
	<atributy>
	  <atribut kod="cat">èíselný identifikátor snímku</atribut>
	  <atribut kod="id">textový identifikátor</atribut>
	  <atribut kod="datum">datum poøízení dat</atribut>
	  <atribut kod="skener">pou¾itý skener</atribut>
	  <atribut kod="nosic">nosiè</atribut>
	  <atribut kod="georef">georeference</atribut>
	  <atribut kod="format">formát dat</atribut> 
	  <atribut kod="uzemi">dotèené státy</atribut>
	  <atribut kod="ul_y">souøadnice Y (S-JTSK) horního levého rohu scény</atribut>
	  <atribut kod="ul_x">souøadnice X (S-JTSK) horního levého rohu scény</atribut>
	  <atribut kod="ll_y">souøadnice Y (S-JTSK) dolního levého rohu scény</atribut>
	  <atribut kod="ll_x">souøadnice X (S-JTSK) dolního levého rohu scény</atribut>
	  <atribut kod="ur_y">souøadnice Y (S-JTSK) horního pravého rohu scény</atribut>
	  <atribut kod="ur_x">souøadnice X (S-JTSK) horního pravého rohu scény</atribut>
	  <atribut kod="lr_y">souøadnice Y (S-JTSK) dolního pravého rohu scény</atribut>
	  <atribut kod="lr_x">souøadnice X (S-JTSK) dolního pravého rohu scény</atribut>
	  <atribut kod="ce_y">souøadnice Y (S-JTSK) støedu scény</atribut>
	  <atribut kod="ce_x">souøadnice X (S-JTSK) støedu scény</atribut>
	  <atribut kod="zona">UTM zóna originálních dat</atribut>
	  <atribut kod="url">URL zdroje dat</atribut>
	</atributy>
	<zdroj title="Global Land Cover Facility">http://glcfapp.umiacs.umd.edu</zdroj>
	<historie text="pøidáno">0.3.0</historie>
      </vrstva> 
      <vrstva id="hranice" stav="0"> 
	<nazev>administrativní hranice</nazev>
	<popis></popis>
	<atributy></atributy>
	<zdroj title="Free maps for Garmin Mapping GPS">http://gps-maps.info/cz</zdroj>
	<zdroj pozn="pouze atributy" title="TopoGuide CZ">
	http://home.tiscali.cz:8080/bytebox/topoguide</zdroj>
	<historie text="pøidáno">0.1.0</historie>
	<historie text="odebráno (nahrazeno kraje_pseudo)">0.2.0</historie>
      </vrstva>  
      <!--
	  <vrstva id="kat_uz" stav="0"> 
	  <nazev>referenèní body katastrálních území</nazev>
	  <popis></popis>
	  <atributy>
	  <atribut kod="kn">identifikátor kraje</atribut>
	  <atribut kod="knok">identifikátor okresu</atribut>
	  <atribut kod="kodnuts">kód NUTS</atribut>
	  <atribut kod="knuts">pracovní kódy okresù</atribut>
	  <atribut kod="kodok">dosud platné kódy okresù</atribut>
	  <atribut kod="kodob">kód obce</atribut>
	  <atribut kod="ko">kontrolní znak</atribut>
	  <atribut kod="icob">identifikaèní èíslo obce</atribut>
	  <atribut kod="porob">poøadí obce v okrese</atribut>
	  <atribut kod="kodku">kód katastrálního úøadu</atribut>
	  <atribut kod="kodku">kód katastrálního úøadu</atribut>
	  <atribut kod="kk"></atribut>
	  <atribut kod="nazku">název katastrálního úøadu</atribut>
	  <atribut kod="nazku_a">název katastrálního úøadu (bez diakritiky)</atribut>
	  <atribut kod="vymera">výmìra obce v ha</atribut>
	  <atribut kod="tu">typ územnì technické jednotky</atribut>
	  <atribut kod="iczuj">identifikaèní èíslo základní územní jednotky</atribut>
	  <atribut kod="pormc">poøadové èíslo mìstské èásti/mìstského obvodu</atribut>
	  <atribut kod="kodocr"></atribut>
	  <atribut kod="kodsra"></atribut>
	  <atribut kod="syku">souøadnice Y v S-JTSK</atribut>
	  <atribut kod="sxku">souøadnice X v S-JTSK</atribut>
	  <atribut kod="mapa">mapový list ZM10</atribut>
	  <atribut kod="nazcs"></atribut>
	  <atribut kod="zmenazaz">zmìna záznamu</atribut>
	  <atribut kod="zmenapol">zmìna polo¾ky</atribut>
	  </atributy>
	  <zdroj pozn="pouze atributy" title="Územnì identifikaèní registr">
	  http://www0.mmr.cz/cgi-bin/sqw1250.cgi/uir/uir.sqw</zdroj>
	  <historie text="pøidáno">0.2.1</historie>
	  </vrstva>
